targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            UUID:
              type: String
            Upload:
              type: MultipartFile
              fromJsonFunctionName: fileFromJson
              toJsonFunctionName: fileToJson
              import: package:manga_love_mobile/graphql_scalars.dart
