name: manga_love_mobile
description: Manga Reader

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.1
  envied: ^0.3.0
  hive: 2.2.3
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  graphql_codegen: ^0.12.0-beta.6
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: 'Merriweather'
      fonts:
        - asset: 'assets/fonts/merriweather/Merriweather-Regular.ttf'
        - asset: 'assets/fonts/merriweather/Merriweather-Bold.ttf'
          weight: 700

flutter_icons:
  image_path: 'assets/launcher-icon.jpg'
  android: true
  ios: true
  web:
    generate: false
  macos:
    generate: false
  windows:
    generate: false